default: &default
  adapter: mysql2
  host: localhost
  username: root
  password: 
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: hackathon2

test:
  <<: *default
  database: hackathon2_test

production:
  adapter: postgresql
  host: ec2-54-217-238-93.eu-west-1.compute.amazonaws.com
  database: d16oltc9c8nk8l
  username: tgbifegxdfrdlj
  port: 5432
  encoding: unicode
  password: mpRPUChZUEkpCXizueXiUyfvR8
