default: &default
  adapter: mysql2
  host: localhost
  username: root
  password: 
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: hackathon2

test:
  <<: *default
  database: hackathon2_test

production:
  adapter: pg
  host: ec2-54-225-136-187.compute-1.amazonaws.com
  username: cfdtdbzqnlxdvn
  database: d8qqa06kds8ssq
  port: 5432
  password: 6K6i2TU5rXHyBovFlNKDowkxKm
